config/routes.rb
Rails.application.routes.draw do
  resources :documented_changes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/documented_change.rb
class DocumentedChange < ApplicationRecord
  validates :summary, length: { maximum: 255 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documented_changes_controller.rb
class DocumentedChangesController < ApplicationController
  before_action :set_documented_change, only: %i[show update destroy]

  def index
    @documented_changes = DocumentedChange.all
  end

  def show; end

  def new
    @documented_change = DocumentedChange.new
  end

  def create
    @documented_change = DocumentedChange.new(documented_change_params)

    if @documented_change.save
      redirect_to documented_change_path(@documented_change)
    else
      # TODO: add flash message
      render :new
    end
  end

  def update
    if @documented_change.update documented_change_params
      redirect_to documented_changes_path
    else
      render :show
    end
  end

  def destroy
    # TODO: add flash message
    @documented_change.destroy
    redirect_to documented_changes_path
  end

  private

  def documented_change_params
    params.require(:documented_change).permit(:summary, :text)
  end

  def set_documented_change
    @documented_change = DocumentedChange.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documented_changes/index.html.erb
<%= render 'shared/load_css' %>

<div class='container'>
  <div class='row'>
    <h1>Documented Changes</h1>
    <div class='col-md-2'>
      <a href="<%= new_documented_change_path %>"
         class='btn btn-primary'
         style='margin-top: 20%;'
      >
        Add New Change
      </a>
    </div>

    <div class='col-md-10'>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th class='col-sm-8'>Summary</th>
            <th class='co-sm-3'>Created</th>
            <th class='col-sm-1'></th>
          </tr>
        </thead>
        <tbody>
          <% @documented_changes.each do |change| %>
            <tr>
              <td>
                <a href="<%= documented_change_path(change) %>">
                  <%= change.summary %>
                </a>
              </td>
              <td><%= change.created_at %></td>
              <td>
                <a href="<%= documented_change_path(change) %>"
                   class='btn btn-danger btn-sm pull-right'
                   data-method='delete'
                   data-confirm='Are you sure you want to delete this change?'
                >
                  X
                </a>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/documented_changes/new.html.erb
<%= render 'shared/load_css' %>

<div class='container'>
  <div class='row'>
    <h3>New Change</h3>
    <div class='col-md-2'>
      <a href="<%= documented_changes_path %>"
         class='btn btn-primary'
         style='margin-top: 20%;'
      >
         Back
      </a>
    </div>

    <div class='col-md-10'>
      <%= form_for @documented_change, url: {action: :create} do |f| %>
        <div class='form-group'>
          <%= label_tag :summary %>
          <%= f.text_area :summary, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= label_tag :text %>
          <%= f.text_area :text, class: 'form-control', rows: 10 %>
        </div>
        <button type='submit' class='btn btn-primary'>Submit</button>
      <% end %>

    </div>
  </div>
</div>

app/views/documented_changes/show.html.erb
<%= render 'shared/load_css' %>

<div class='container'>
  <div class='row'>
    <h2>
      <%= @documented_change.summary %>
    </h2>

    <div class='col-md-2'>
      <a href="<%= documented_changes_path %>"
         class='btn btn-primary'
         style='margin-top: 20%;'
      >
         Back
      </a>
    </div>

    <div class='col-md-10'>
      <%= form_for @documented_change, url: {action: :update} do |f| %>
        <div class='form-group'>
          <%= label_tag :summary %>
          <%= f.text_area :summary, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= label_tag :text %>
          <%= f.text_area :text, class: 'form-control', rows: 10 %>
        </div>
        <button type='submit' class='btn btn-primary'>Submit</button>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HunkyDory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_load_css.html.erb
<%= stylesheet_link_tag    'hunky_dory/application', media: 'all', 'data-turbolinks-track': 'reload' %>